"""adding type to post

Revision ID: 351b4d48b410
Revises: b81a90232380
Create Date: 2026-02-25 14:30:11.627893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351b4d48b410'
down_revision = 'b81a90232380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
